## Google Drive locations for pre-run simulation objects
## these are used when config option 'prerun' is true

gdriveURL <- "https://drive.google.com/drive/folders/1pFpAZwFqRIWxAygntEx8rVPV_b2BTqMB/"

gdriveSims <- switch(
  studyAreaName,
  AB = list(
    simOutPreamble = "1_uE5DsjvSDmcRJxoNCs5izr2uYtGSImy",
    simOutPreambleArchive = "",
    biomassMaps2001 = "1cU2e0GFE4Ti_E5vBQy9TTXU-mzRL3xjV",
    biomassMaps2001Archive = "",
    biomassMaps2011 = "1bMkZQnW4ELiy7la1etMAGFA7O33ooE-h",
    biomassMaps2011Archive = "",
    fSsimDataPrep = "1qwEw_NvXfqpZSrILmT9ZOORRLXF6DuI3",
    fSsimDataPrepArchive = "",
    ignitionOut = "",
    ignitionOutArchive = "",
    escapeOut = "1qv-wPPxljrjHVQRZ2V6Y2NsC8iQ9T-5i",
    escapeOutArchive = "",
    spreadOut = "",
    spreadOutArchive = ""
  ),
  BC = list(
    simOutPreamble = "1edMzH3E4q1f7kdmdSRFcuEEE1MdegUWc",
    simOutPreambleArchive = "",
    biomassMaps2001 = "12iGj3nAgr5fdKidf5ru32A6voCVC-qQx",
    biomassMaps2001Archive = "",
    biomassMaps2011 = "18xPAviLGUuN8XFINLBDmpAkKBh-C0ybV",
    biomassMaps2011Archive = "",
    fSsimDataPrep = "1fCvpQ7w6-jjyLB7kjKL6L5d1dfyOaIkJ",
    fSsimDataPrepArchive = "",
    ignitionOut = "",
    ignitionOutArchive = "",
    escapeOut = "18Xmo72ZhDoDRXSv1BFrhBJp4sqQnbZsx",
    escapeOutArchive = "",
    spreadOut = "",
    spreadOutArchive = ""
  ),
  MB = list(
    simOutPreamble = "1WznBdEwuo9lBK1xkOw9P84dKrcn3OasT",
    simOutPreambleArchive = "",
    biomassMaps2001 = "1PqeJWDh1ZBVHPokqJ9Hjmr0ZBEUbNHKi",
    biomassMaps2001Archive = "",
    biomassMaps2011 = "1xC9pSM3P22106uN4XekTWlE7lpYgP5_I",
    biomassMaps2011Archive = "",
    fSsimDataPrep = "1CDV5a-0IXJA0cJWroqSmkJGJQBUTRSxS",
    fSsimDataPrepArchive = "",
    ignitionOut = "1u7LBgwWi23YnpmN2xLdt8Og1tNHkS4xq",
    ignitionOutArchive = "",
    escapeOut = "1fYvOci3zofb4yRluiaTl6NrVFFa738Yc",
    escapeOutArchive = "",
    spreadOut = "1S898TKgz1GkVsBQJX9-LQk5S2_Sr8CXA",
    spreadOutArchive = ""
  ),
  NT = list(
    simOutPreamble = "1gx09K9gbBcKgV43-n3Le-u5_-8EQe4pr",
    simOutPreambleArchive = "10OMvnSIXfuQUBmBWxHC4rvufT0mJeE7W",
    biomassMaps2001 = "1wAoje96tK15b8Ovg6gtR16HHCb4t_49A",
    biomassMaps2001Archive = "",
    biomassMaps2011 = "1cSSbADBd-6LPBvnfbY8vefu8I4iFygsu",
    biomassMaps2011Archive = "",
    fSsimDataPrep = "1kla8pX3_QmPW3ZY_R8cdFQQah5NFc2-S",
    fSsimDataPrepArchive = "",
    ignitionOut = "",
    ignitionOutArchive = "",
    escapeOut = "1RNuOUxff8oQVHL6Gx7AWm2UJ4LwT0Nf_",
    escapeOutArchive = "",
    spreadOut = "1NJp3j-F9Y8_6hqVaEB1eExrulGtwTvEb",
    spreadOutArchive = ""
  ),
  SK = list(
    simOutPreamble = "1ZjbUFqaZZLV60WVPXaO2ZnMUepiU8ju9",
    simOutPreambleArchive = "",
    biomassMaps2001 = "1iqBhXSeCJTMV331ufWjTQk7n-jMekN0s",
    biomassMaps2001Archive = "1AyTUaFkgoSN0o6hsai_VrYgHzoG8Uww1",
    biomassMaps2011 = "1AxtVqPdoV1NJ_UUhIjnwrygGCIpTMann",
    biomassMaps2011Archive = "10CBmVgfMdtyBjJ07V1_4sm6_axq_0wja",
    fSsimDataPrep = "1d8LBNwbKQ9NRxr8laFctLJGbplqcwpFa",
    fSsimDataPrepArchive = "",
    ignitionOut = "1p-tuk10npiGU4-doLmk5d_xmMgLb8uli",
    ignitionOutArchive = "",
    escapeOut = "1DZVT7q5ST1sHlHPUW04u0SOADJOqZOn_",
    escapeOutArchive = "",
    spreadOut = "13B86O_u4c3u5angB6jWGBfIhiv_M7R4b",
    spreadOutArchive = ""
  ),
  YT = list(
    simOutPreamble = "1U1UHf7lWEiBjtc51Lftn-He56S2MIjk6",
    simOutPreambleArchive = "",
    biomassMaps2001 = "165N8zzQa0IxZHLZMjhYZbQ85K1Ca12aW",
    biomassMaps2001Archive = "",
    biomassMaps2011 = "1gMFRn3NBEUNhMg43cJSH6GLcgQ-PYXqc",
    biomassMaps2011Archive = "",
    fSsimDataPrep = "1Gkkzet1rIUF4Ahc8aSB3dQwSeCCdSxKR",
    fSsimDataPrepArchive = "",
    ignitionOut = "",
    ignitionOutArchive = "",
    escapeOut = "1EGlPDzu6BSlW2cj7otNnlZf4JBqzKm-J",
    escapeOutArchive = "",
    spreadOut = "18CsY1Vw1s8bqEas-2fwO3CSmgQ4m7x_D",
    spreadOutArchive = ""
  ),
  RIA = list(
   simOutPreamble = "17e6HBZlRAj27V4cwapm7WhtJZbY7quQt",
   simOutPreambleArchive = "",
   biomassMaps2001 = "1aUdgIIxewXbj963vwc9lTmU5Y5TswRNj",
   biomassMaps2001Archive = "",
   biomassMaps2011 = "1gc-9A5KqJCdK0x1PEjTi_ZzL4VUQDjsD",
   biomassMaps2011Archive = "",
   fSsimDataPrep = "1Lh8aCZX8zt7kCSY-vv9GqVfhS2CK-Jgv",
   fSsimDataPrepArchive = "",
   ignitionOut = "1hRYjTObyMd1T4kiO-bETgRuyEzn_miz_",
   ignitionOutArchive = "11y-DeXBm7wpXVcZw7A7cODfYiiW3_TRR",
   escapeOut = "1LLPdaVtPSCDuoookq8G1JWUzoGb3SHTW",
   escapeOutArchive = "1C1ZSmWluwtCDW5o-zj-Rtmbqf7Y46UyB",
   spreadOut = "",
   spreadOutArchive = ""
 )
)
