default:
  batchmode: false
  cachedb: "sqlite"
  cloud:
    cachedir: ""
    googleuser: ""
    usecloud: false
  mapresfact: 1
  paths:
    cachedir: "cache"
    scratchdir: "/tmp/scratch/WBI_fireSense"
  plot: true
  studyarea: "RIA" ## AB, BC, SK, MB, YT, NT, NU

production:
  batchmode: true
  plot: false

alex:
  inherits: production
  cachedb: "postgresql"
  cloud:
    cachedir: ""
    googleuser: "achubaty@for-cast.ca"
    usecloud: false ## TODO: use cloud cache
  paths:
    scratchdir: !expr if (Sys.info()[["nodename"]] == "forcast01") "/mnt/scratch/WBI_fireSense" else "/tmp/scratch/WBI_fireSense"
  slackchannel: "@alex.chubaty"

ian:
  cachedb: "sqlite"
  cloud:
    cachedir: ""
    googleuser: 'ianmseddy@gmail.com'
    usecloud: true
  paths:
    scratchdir:  !expr if (Sys.info()[["nodename"]] == "W-VIC-A127551") "D:/Ian/scratch" else '/mnt/scratch/ieddy/'

