default:
  batchmode: false
  cachedb: "sqlite"
  googleuser: ""
  mapresfact: 1
  paths:
    cachedir: "cache"
    scratchdir: "/tmp/scratch/WBI_fireSense"
  plot: true

production:
  batchmode: true
  plot: false

alex:
  inherits: production
  cachedb: "postgresql"
  googleuser: "achubaty@for-cast.ca"
  paths:
    scratchdir: !expr if (Sys.info()[["nodename"]] == "forcast03") "/tmp/scratch/WBI_fireSense" else "/mnt/scratch/WBI_fireSense"
  slackchannel: "@alex.chubaty"

ian:
  cachedb: 'sqlite'
  googleuser: 'ianmseddy@gmail.com'
  paths:
    scratchdir:  !expr if (Sys.info()[["nodename"]] == "W-VIC-A127551") "D:/Ian/scratch" else '/mnt/scratch/ieddy/'

