default:
  batchmode: false
  cachedb: "sqlite"
  cacheformat: "qs"
  cloud:
    cachedir: "1vuXsTRma-vySEAvkofP8aTUqZhUVsxd0"
    googleuser: ""
    usecloud: false
  codechecks: true
  inputpaths: null
  mapresfact: 1
  paths:
    cachedir: "cache"
    scratchdir: "/tmp/scratch/WBI_fireSense"
  plot: true
  reproduciblealgorithm: 1
  studyarea: "RIA" ## AB, BC, SK, MB, YT, NT, NU, RIA
  usememoise: false
  userequire: true

production:
  batchmode: true
  codechecks: false
  plot: false

alex:
  inherits: production
  cachedb: "postgresql"
  cacheformat: "qs"
  cloud:
    #cachedir: ""
    googleuser: "achubaty@for-cast.ca"
    usecloud: false ## TODO: use cloud cache
  codechecks: true ## TODO: set false after all fixed
  paths:
    scratchdir: !expr if (Sys.info()[["nodename"]] == "forcast01") "/mnt/scratch/WBI_fireSense" else "/tmp/scratch/WBI_fireSense"
  slackchannel: "@alex.chubaty"

ian:
  cachedb: "sqlite"
  cacheformat: "qs"
  cloud:
    #cachedir: ""
    googleuser: 'ianmseddy@gmail.com'
    usecloud: false
  codechecks: true ## TODO: set false after all fixed
  reproduciblealgorithm: 2 #use old digest
  paths:
    scratchdir: !expr if (Sys.info()[["nodename"]] == "W-VIC-A127551") "D:/Ian/scratch" else '/mnt/scratch/ieddy/'

eliot:
  cachedb: "sqlite"
  cacheformat: "qs"
  cloud:
    #cachedir: ""
    googleuser: 'eliotmcintire@gmail.com'
    usecloud: false
  codechecks: false
  inputpaths: ~/data
  paths:
    scratchdir: "/tmp/scratch/WBI_fireSense"
  reproduciblealgorithm: 2
  usememoise: true
